[package]
name = "qvm"
version = "0.1.0"
authors = ["Sam Westerman <sam.westerman@usaepay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
